[package]
name = "game-util"
version = "0.1.0"
authors = ["MinusKelvin <mark.carlson@minuskelvin.net>"]
edition = "2018"

[dependencies]
euclid = { version = "0.22", features = ["serde"] }
glow = "0.7"
winit = { version = "0.24", features = ["serde", "web-sys"] }
rusttype = { version = "0.9", features = ["gpu_cache"] }
serde = { version = "1.0", features = ["derive"] }
arrayvec = "0.5"
scopeguard = "1.1"
lazy_static = "1.4"
instant = "0.1"
futures = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.26"
rodio = "0.13"
image = "0.23"

[target.'cfg(target_arch = "wasm32")'.dependencies]
webutil = { git = "https://github.com/MinusKelvin/webutil", rev = "5a54126" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
    "Response",
    "Blob",
    "Url",
    "AudioContext",
    "AudioBuffer",
    "AudioBufferSourceNode",
    "AudioDestinationNode",
    "AudioParam",
    "GainNode",
    "ConstantSourceNode"
]
